package dev.jwillert.kopetal.forms.components

import dev.jwillert.kopetal.ButtonKey
import dev.jwillert.kopetal.InputKey
import dev.jwillert.kopetal.KopetalRegistry

// Auto-generated by addComponent — do not edit manually
object KopetalComponents {
    fun configure() {
        KopetalRegistry[ButtonKey] = { label, disabled, block -> koButton(label = label, disabled = disabled, block = block) }
        KopetalRegistry[InputKey] = { name, type, required, block -> koInput(name = name, type = type, required = required, block = block) }
    }
}
