package dev.jwillert.ktor.daisyui.tasks

fun generateConfigureStatement(entry: ComponentEntry): String? {
    val registryFqn = entry.slotRegistryClass ?: return null
    val keyFqn = entry.slotKey ?: return null
    val params = entry.slotParams ?: return null
    val registrySimpleName = registryFqn.substringAfterLast(".")
    val keySimpleName = keyFqn.substringAfterLast(".")
    val paramNames = params.split(",").map { it.trim().substringBefore(":").trim() }
    val args = paramNames.joinToString(", ") { "$it = $it" }
    val fnName = "ko${entry.name.replaceFirstChar { it.uppercaseChar() }}"
    return "$registrySimpleName[$keySimpleName] = { ${paramNames.joinToString(", ")} -> $fnName($args) }"
}

fun generateKopetalComponentsContent(
    installedNames: Set<String>,
    allRegistryEntries: List<ComponentEntry>,
    packageName: String,
): String {
    val slotEntries = allRegistryEntries.filter { entry ->
        entry.name in installedNames &&
            entry.slotRegistryClass != null &&
            entry.slotKey != null &&
            entry.slotParams != null
    }
    if (slotEntries.isEmpty()) return ""

    val imports = (
        slotEntries.mapNotNull { it.slotRegistryClass } +
            slotEntries.mapNotNull { it.slotKey }
        ).distinct().sorted()

    val statements = slotEntries.mapNotNull { generateConfigureStatement(it) }

    return buildString {
        appendLine("package $packageName")
        appendLine()
        imports.forEach { appendLine("import $it") }
        appendLine()
        appendLine("// Auto-generated by addComponent — do not edit manually")
        appendLine("object KopetalComponents {")
        appendLine("    fun configure() {")
        statements.forEach { appendLine("        $it") }
        appendLine("    }")
        append("}")
    }
}
